// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxoxfhhwbavniybllumy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94b3hmaGh3YmF2bml5YmxsdW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxODU0NTQsImV4cCI6MjA1MTc2MTQ1NH0.0O-GRt3sIcoVM5hIJoI2s0O59tYAOOKNF5PuUqdqtec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);